package IsoEngine
{
   import Data.Texts;
   
   public class WeaponsData
   {
      
      public static var AnimationTypes:* = [0,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,4,3,3,3,5,6,4,4,0,4,4,5,5];
      
      public static const DroppedWeaponsPoints:* = [[70,3272],[70,3172],[74,3373],[61,2275],[68,2277],[75,2271],[60,2380]];
      
      public static var WeaponTypes:* = [{
         "name":281,
         "modes":[{
            "name":790,
            "AP":3,
            "hitProbability":1,
            "damageMultiplier":0.8
         },{
            "name":791,
            "AP":4,
            "hitProbability":0.9,
            "damageMultiplier":1.2
         }],
         "category":0
      },{
         "name":282,
         "modes":[{
            "name":792,
            "AP":4,
            "hitProbability":1.3,
            "damageMultiplier":0.7
         },{
            "name":793,
            "AP":3,
            "hitProbability":0.7,
            "damageMultiplier":1
         }],
         "category":1
      },{
         "name":778,
         "modes":[{
            "name":794,
            "AP":4,
            "hitProbability":1,
            "damageMultiplier":0.9
         },{
            "name":795,
            "AP":6,
            "hitProbability":0.9,
            "damageMultiplier":1.5
         }],
         "category":1
      },{
         "name":284,
         "modes":[{
            "name":796,
            "AP":3,
            "accuracy":0.8
         },{
            "name":797,
            "AP":4,
            "accuracy":1,
            "aimed":true
         },{
            "name":798,
            "AP":6,
            "accuracy":0.5,
            "damageMultiplier":2.5,
            "headShot":true
         }],
         "reloadAP":3,
         "category":2,
         "subCategory":1
      },{
         "name":285,
         "modes":[{
            "name":796,
            "AP":5,
            "accuracy":0.8
         },{
            "name":797,
            "AP":7,
            "accuracy":1.2,
            "aimed":true
         },{
            "name":798,
            "AP":9,
            "accuracy":0.6,
            "damageMultiplier":2.5,
            "headShot":true
         }],
         "reloadAP":3,
         "category":2,
         "subCategory":2
      },{
         "name":286,
         "modes":[{
            "name":799,
            "AP":7,
            "accuracy":0.7,
            "burst":3
         },{
            "name":796,
            "AP":4,
            "accuracy":1
         }],
         "reloadAP":3,
         "category":2,
         "subCategory":4
      },{
         "name":287,
         "modes":[{
            "name":800,
            "AP":5,
            "accuracy":1
         },{
            "name":801,
            "AP":6,
            "accuracy":1,
            "parallelShots":2
         }],
         "reloadAP":6,
         "category":2,
         "subCategory":5
      },{
         "name":288,
         "modes":[{
            "name":796,
            "AP":5,
            "accuracy":0.8
         },{
            "name":797,
            "AP":6,
            "accuracy":1.1,
            "aimed":true
         },{
            "name":798,
            "AP":7,
            "accuracy":0.7,
            "damageMultiplier":2.5,
            "headShot":true
         }],
         "reloadAP":7,
         "category":3,
         "subCategory":1
      },{
         "name":289,
         "modes":[{
            "name":802,
            "AP":6,
            "accuracy":1,
            "burst":30
         },{
            "name":803,
            "AP":7,
            "accuracy":1,
            "burst":40
         }],
         "reloadAP":4,
         "category":4
      },{
         "name":290,
         "modes":[{
            "name":804,
            "AP":5,
            "accuracy":1
         }],
         "reloadAP":7,
         "category":3,
         "subCategory":2
      },{
         "name":291,
         "modes":[{
            "name":59,
            "AP":5,
            "accuracy":1
         }],
         "category":5
      },{
         "name":779,
         "modes":[{
            "name":796,
            "AP":3,
            "accuracy":0.7
         },{
            "name":797,
            "AP":5,
            "accuracy":1.1,
            "aimed":true
         },{
            "name":798,
            "AP":6,
            "accuracy":0.5,
            "damageMultiplier":2.5,
            "headShot":true
         }],
         "reloadAP":6,
         "category":2,
         "subCategory":1
      },{
         "name":780,
         "modes":[{
            "name":796,
            "AP":3,
            "accuracy":0.8
         },{
            "name":797,
            "AP":5,
            "accuracy":1,
            "aimed":true
         },{
            "name":798,
            "AP":6,
            "accuracy":0.5,
            "damageMultiplier":2.5,
            "headShot":true
         }],
         "reloadAP":8,
         "category":2,
         "subCategory":1
      },{
         "name":781,
         "modes":[{
            "name":796,
            "AP":6,
            "accuracy":0.8
         },{
            "name":797,
            "AP":8,
            "accuracy":1.2,
            "aimed":true
         },{
            "name":798,
            "AP":10,
            "accuracy":0.6,
            "damageMultiplier":2.5,
            "headShot":true
         }],
         "reloadAP":3,
         "category":2,
         "subCategory":2
      },{
         "name":782,
         "modes":[{
            "name":796,
            "AP":5,
            "accuracy":0.8
         },{
            "name":797,
            "AP":7,
            "accuracy":1.2,
            "aimed":true
         },{
            "name":798,
            "AP":9,
            "accuracy":0.6,
            "damageMultiplier":2.5,
            "headShot":true
         }],
         "reloadAP":8,
         "category":2,
         "subCategory":2
      },{
         "name":783,
         "modes":[{
            "name":796,
            "AP":5,
            "accuracy":0.8
         },{
            "name":797,
            "AP":7,
            "accuracy":1.1,
            "aimed":true
         },{
            "name":798,
            "AP":9,
            "accuracy":0.5,
            "damageMultiplier":2.5,
            "headShot":true
         },{
            "name":799,
            "AP":8,
            "accuracy":0.6,
            "burst":3
         },{
            "name":799,
            "AP":12,
            "accuracy":0.6,
            "burst":5
         }],
         "reloadAP":3,
         "category":2,
         "subCategory":2
      },{
         "name":784,
         "modes":[{
            "name":799,
            "AP":7,
            "accuracy":0.9,
            "burst":3
         },{
            "name":799,
            "AP":9,
            "accuracy":0.8,
            "burst":5
         },{
            "name":799,
            "AP":12,
            "accuracy":0.7,
            "burst":8
         },{
            "name":799,
            "AP":15,
            "accuracy":0.7,
            "burst":12
         }],
         "reloadAP":7,
         "category":2,
         "subCategory":3
      },{
         "name":785,
         "modes":[{
            "name":796,
            "AP":6,
            "accuracy":1
         }],
         "reloadAP":6,
         "category":2,
         "subCategory":5
      },{
         "name":786,
         "modes":[{
            "name":796,
            "AP":5,
            "accuracy":1
         }],
         "reloadAP":4,
         "category":2,
         "subCategory":5
      },{
         "name":787,
         "modes":[{
            "name":794,
            "AP":3,
            "hitProbability":1,
            "damageMultiplier":0.7
         },{
            "name":795,
            "AP":5,
            "hitProbability":0.9,
            "damageMultiplier":1.2
         }],
         "category":1
      },{
         "name":788,
         "modes":[{
            "name":794,
            "AP":4,
            "hitProbability":1,
            "damageMultiplier":1
         },{
            "name":795,
            "AP":6,
            "hitProbability":0.9,
            "damageMultiplier":1.7
         },{
            "name":793,
            "AP":3,
            "hitProbability":0.6,
            "damageMultiplier":1.2
         }],
         "category":1
      },{
         "name":789,
         "modes":[{
            "name":796,
            "AP":7,
            "accuracy":1
         }],
         "reloadAP":6,
         "category":2,
         "subCategory":5
      },{
         "name":783,
         "modes":[{
            "name":796,
            "AP":5,
            "accuracy":1
         },{
            "name":799,
            "AP":8,
            "accuracy":0.8,
            "burst":3
         },{
            "name":799,
            "AP":12,
            "accuracy":0.8,
            "burst":5
         }],
         "reloadAP":3,
         "category":2,
         "subCategory":5
      },{
         "name":288,
         "modes":[{
            "name":796,
            "AP":4,
            "accuracy":0.8
         },{
            "name":797,
            "AP":5,
            "accuracy":1.1,
            "aimed":true
         },{
            "name":798,
            "AP":7,
            "accuracy":0.7,
            "damageMultiplier":2.5,
            "headShot":true
         }],
         "reloadAP":5,
         "category":3,
         "subCategory":1
      },{
         "name":4222,
         "modes":[{
            "name":790,
            "AP":3,
            "hitProbability":1,
            "damageMultiplier":0.8
         },{
            "name":791,
            "AP":4,
            "hitProbability":0.9,
            "damageMultiplier":1.2
         }],
         "category":1
      },{
         "name":4224,
         "modes":[{
            "name":800,
            "AP":5,
            "accuracy":1
         }],
         "reloadAP":5,
         "category":2,
         "subCategory":5
      },{
         "name":4236,
         "modes":[{
            "name":799,
            "AP":5,
            "accuracy":0.9,
            "burst":3
         },{
            "name":799,
            "AP":7,
            "accuracy":0.8,
            "burst":5
         },{
            "name":796,
            "AP":4,
            "accuracy":1
         }],
         "reloadAP":3,
         "category":2,
         "subCategory":4
      },{
         "name":6795,
         "modes":[{
            "name":799,
            "AP":7,
            "accuracy":0.9,
            "burst":6
         },{
            "name":799,
            "AP":9,
            "accuracy":0.8,
            "burst":10
         },{
            "name":799,
            "AP":12,
            "accuracy":0.7,
            "burst":16
         },{
            "name":799,
            "AP":15,
            "accuracy":0.7,
            "burst":24
         }],
         "reloadAP":7,
         "category":2,
         "subCategory":3
      },{
         "name":7094,
         "modes":[{
            "name":796,
            "AP":2,
            "accuracy":0.8
         },{
            "name":797,
            "AP":4,
            "accuracy":1,
            "aimed":true
         },{
            "name":798,
            "AP":6,
            "accuracy":0.5,
            "damageMultiplier":2.5,
            "headShot":true
         }],
         "reloadAP":3,
         "category":2,
         "subCategory":1
      }];
      
      public static var Weapons:* = [{
         "name":1024,
         "type":0,
         "animatedWeapon":0,
         "range":1,
         "armorNeutralization":0,
         "openWoundCoeficient":0.002,
         "weight":0,
         "sound":["SFXPunch1","SFXPunch2","SFXPunch3","SFXPunch4","SFXPunch5"]
      },{
         "name":1025,
         "type":1,
         "animatedWeapon":1,
         "range":1,
         "baseDamage":8,
         "armorNeutralization":1,
         "openWoundCoeficient":0.02,
         "weight":0.2,
         "doctorImprove":0.05,
         "veterinaryImprove":0.05,
         "mechanicImprove":0.01,
         "price":75,
         "sound":["SFXKnifeHit1","SFXKnifeHit2","SFXKnifeHit3","SFXKnifeHit4"]
      },{
         "name":1026,
         "type":1,
         "animatedWeapon":2,
         "range":1,
         "baseDamage":10,
         "armorNeutralization":0,
         "openWoundCoeficient":0.02,
         "weight":0.4,
         "doctorImprove":0.05,
         "veterinaryImprove":0.05,
         "mechanicImprove":0.01,
         "price":90,
         "sound":["SFXKnifeHit1","SFXKnifeHit2","SFXKnifeHit3","SFXKnifeHit4"]
      },{
         "name":1027,
         "type":2,
         "animatedWeapon":3,
         "range":1,
         "baseDamage":9,
         "armorNeutralization":5,
         "openWoundCoeficient":0.002,
         "weight":1.2,
         "price":25,
         "sound":["SFXMeleeHit1","SFXMeleeHit2","SFXMeleeHit3","SFXMeleeHit4","SFXMeleeHit5","SFXMeleeHit6"]
      },{
         "name":1028,
         "type":2,
         "animatedWeapon":4,
         "range":1,
         "baseDamage":11,
         "armorNeutralization":8,
         "openWoundCoeficient":0.003,
         "weight":2.5,
         "price":36,
         "sound":["SFXMeleeHit1","SFXMeleeHit2","SFXMeleeHit3","SFXMeleeHit4","SFXMeleeHit5","SFXMeleeHit6"]
      },{
         "name":1029,
         "type":2,
         "animatedWeapon":5,
         "range":1,
         "baseDamage":13,
         "armorNeutralization":15,
         "openWoundCoeficient":0.003,
         "weight":1.3,
         "price":81,
         "sound":["SFXMeleeHit1","SFXMeleeHit2","SFXMeleeHit3","SFXMeleeHit4","SFXMeleeHit5","SFXMeleeHit6"]
      },{
         "name":1030,
         "type":2,
         "animatedWeapon":6,
         "range":1,
         "baseDamage":11,
         "armorNeutralization":10,
         "openWoundCoeficient":0.003,
         "mechanicImprove":0.15,
         "weight":2,
         "price":49,
         "sound":["SFXMeleeHit1","SFXMeleeHit2","SFXMeleeHit3","SFXMeleeHit4","SFXMeleeHit5","SFXMeleeHit6"]
      },{
         "name":1031,
         "type":19,
         "animatedWeapon":7,
         "range":1,
         "baseDamage":18,
         "armorNeutralization":0,
         "openWoundCoeficient":0.04,
         "weight":0.8,
         "price":144,
         "sound":["SFXKnifeHit1","SFXKnifeHit2","SFXKnifeHit3","SFXKnifeHit4"]
      },{
         "name":1032,
         "type":19,
         "animatedWeapon":8,
         "range":1,
         "baseDamage":20,
         "armorNeutralization":0,
         "openWoundCoeficient":0.03,
         "collectingImprove":0.2,
         "weight":1.1,
         "price":256,
         "sound":["SFXKnifeHit1","SFXKnifeHit2","SFXKnifeHit3","SFXKnifeHit4"]
      },{
         "name":1033,
         "type":19,
         "animatedWeapon":9,
         "range":1,
         "baseDamage":25,
         "armorNeutralization":10,
         "openWoundCoeficient":0.03,
         "weight":1.9,
         "price":400,
         "sound":["SFXKnifeHit1","SFXKnifeHit2","SFXKnifeHit3","SFXKnifeHit4"]
      },{
         "name":1034,
         "type":2,
         "animatedWeapon":10,
         "range":1,
         "baseDamage":17,
         "armorNeutralization":25,
         "openWoundCoeficient":0.01,
         "weight":2.5,
         "price":361,
         "sound":["SFXMeleeHit1","SFXMeleeHit2","SFXMeleeHit3","SFXMeleeHit4","SFXMeleeHit5","SFXMeleeHit6"]
      },{
         "name":1035,
         "type":2,
         "animatedWeapon":11,
         "range":1,
         "baseDamage":15,
         "armorNeutralization":20,
         "openWoundCoeficient":0.005,
         "weight":2.3,
         "price":262,
         "sound":["SFXMeleeHit1","SFXMeleeHit2","SFXMeleeHit3","SFXMeleeHit4","SFXMeleeHit5","SFXMeleeHit6"]
      },{
         "name":1036,
         "type":2,
         "animatedWeapon":12,
         "range":1,
         "baseDamage":20,
         "armorNeutralization":15,
         "openWoundCoeficient":0.02,
         "weight":2.6,
         "price":576,
         "sound":["SFXMeleeHit1","SFXMeleeHit2","SFXMeleeHit3","SFXMeleeHit4","SFXMeleeHit5","SFXMeleeHit6"]
      },{
         "name":1037,
         "type":2,
         "animatedWeapon":13,
         "range":1,
         "baseDamage":25,
         "armorNeutralization":35,
         "openWoundCoeficient":0.005,
         "weight":4,
         "price":900,
         "sound":["SFXMeleeHit1","SFXMeleeHit2","SFXMeleeHit3","SFXMeleeHit4","SFXMeleeHit5","SFXMeleeHit6"]
      },{
         "name":1038,
         "type":19,
         "animatedWeapon":14,
         "range":1,
         "baseDamage":35,
         "armorNeutralization":25,
         "openWoundCoeficient":0.05,
         "weight":6.3,
         "price":1600,
         "sound":["SFXSwordHit1"]
      },{
         "name":1039,
         "type":2,
         "animatedWeapon":15,
         "range":1,
         "baseDamage":25,
         "armorNeutralization":40,
         "openWoundCoeficient":0.003,
         "mechanicImprove":0.1,
         "weight":8.2,
         "price":1444,
         "sound":["SFXMeleeHit1","SFXMeleeHit2","SFXMeleeHit3","SFXMeleeHit4","SFXMeleeHit5","SFXMeleeHit6"]
      },{
         "name":1040,
         "type":20,
         "animatedWeapon":16,
         "range":1,
         "baseDamage":40,
         "armorNeutralization":0,
         "openWoundCoeficient":0.06,
         "weight":1,
         "price":5776,
         "sound":["SFXSwordHit1","SFXSwordHit2","SFXSwordHit3"]
      },{
         "name":1041,
         "type":20,
         "animatedWeapon":17,
         "range":1,
         "baseDamage":35,
         "armorNeutralization":5,
         "openWoundCoeficient":0.055,
         "weight":1.1,
         "price":3721,
         "sound":["SFXSwordHit1","SFXSwordHit2","SFXSwordHit3"]
      },{
         "name":1042,
         "type":20,
         "animatedWeapon":18,
         "range":1,
         "baseDamage":38,
         "armorNeutralization":10,
         "openWoundCoeficient":0.05,
         "weight":1.4,
         "price":5184,
         "sound":["SFXSwordHit1","SFXSwordHit2","SFXSwordHit3"]
      },{
         "name":1043,
         "type":20,
         "animatedWeapon":19,
         "range":1,
         "baseDamage":35,
         "armorNeutralization":0,
         "openWoundCoeficient":0.055,
         "weight":1.2,
         "price":3600,
         "sound":["SFXSwordHit1","SFXSwordHit2","SFXSwordHit3"]
      },{
         "name":1044,
         "type":3,
         "animatedWeapon":20,
         "range":150,
         "accuracy":5,
         "weight":0.871,
         "ammo":1,
         "ammoCapacity":8,
         "muzzleVelocityChange":0,
         "price":3500,
         "sound":"SFXPistol1"
      },{
         "name":1045,
         "type":4,
         "animatedWeapon":21,
         "range":400,
         "accuracy":10,
         "weight":4.31,
         "ammo":2,
         "ammoCapacity":8,
         "muzzleVelocityChange":0.03,
         "price":10000,
         "sound":"SFXRifle1"
      },{
         "name":1046,
         "type":6,
         "animatedWeapon":22,
         "range":100,
         "accuracy":3,
         "weight":2.2,
         "ammo":3,
         "ammoCapacity":2,
         "muzzleVelocityChange":-0.1,
         "spread":0.3,
         "price":6400,
         "sound":["SFXShotgun1","SFXShotgun2","SFXShotgun3"]
      },{
         "name":1047,
         "type":5,
         "animatedWeapon":23,
         "range":100,
         "accuracy":3,
         "weight":3.5,
         "ammo":1,
         "ammoCapacity":32,
         "muzzleVelocityChange":0.02,
         "price":9216,
         "sound":["SFXSMG1","SFXSMG2","SFXSMG3"]
      },{
         "name":1048,
         "type":23,
         "animatedWeapon":24,
         "range":100,
         "accuracy":5,
         "weight":1.5,
         "ammo":4,
         "ammoCapacity":1,
         "arrowSpeed":60,
         "price":900,
         "sound":"SFXCrossbow1"
      },{
         "name":1049,
         "type":8,
         "animatedWeapon":25,
         "range":6,
         "accuracy":5,
         "weight":7,
         "ammo":5,
         "ammoCapacity":200,
         "bigGunBackpack":1,
         "price":23400
      },{
         "name":1050,
         "type":9,
         "animatedWeapon":26,
         "range":100,
         "accuracy":6,
         "weight":5.9,
         "ammo":6,
         "ammoCapacity":1,
         "arrowSpeed":75,
         "price":45000,
         "sound":"SFXRocketLauncher1"
      },{
         "name":1051,
         "type":10,
         "animatedWeapon":0,
         "weight":0.4,
         "explosiveness":35,
         "antiPersonnel":15,
         "flame":false,
         "explodeOnImpact":false,
         "delay":3,
         "price":6000,
         "sound":"SFXPunchSwoosh"
      },{
         "name":1052,
         "type":10,
         "animatedWeapon":0,
         "weight":0.8,
         "explosiveness":25,
         "antiPersonnel":0,
         "flame":true,
         "explodeOnImpact":true,
         "delay":5,
         "price":200,
         "sound":"SFXPunchSwoosh"
      },{
         "name":288,
         "type":7,
         "animatedWeapon":27,
         "range":200,
         "accuracy":7,
         "weight":3,
         "ammo":4,
         "ammoCapacity":1,
         "arrowSpeed":75,
         "price":2300,
         "sound":"SFXCrossbow1"
      },{
         "name":3889,
         "type":15,
         "animatedWeapon":28,
         "range":300,
         "accuracy":8,
         "weight":3.26,
         "ammo":7,
         "ammoCapacity":30,
         "muzzleVelocityChange":0.01,
         "price":40000,
         "sound":["SFXM161","SFXM162","SFXM163"]
      },{
         "name":3912,
         "type":7,
         "animatedWeapon":27,
         "range":300,
         "accuracy":9,
         "weight":3,
         "ammo":4,
         "ammoCapacity":1,
         "arrowSpeed":150,
         "price":18000,
         "sound":"SFXCrossbow1"
      },{
         "name":4059,
         "type":19,
         "animatedWeapon":9,
         "range":1,
         "baseDamage":20,
         "armorNeutralization":10,
         "openWoundCoeficient":0.03,
         "weight":1.9,
         "price":800,
         "sound":["SFXKnifeHit1","SFXKnifeHit2","SFXKnifeHit3","SFXKnifeHit4"]
      },{
         "name":4175,
         "type":13,
         "animatedWeapon":21,
         "range":400,
         "accuracy":11,
         "weight":4,
         "ammo":8,
         "ammoCapacity":10,
         "muzzleVelocityChange":0.04,
         "price":8500,
         "sound":"SFXRifle1"
      },{
         "name":4180,
         "type":13,
         "animatedWeapon":21,
         "range":400,
         "accuracy":11,
         "weight":4,
         "ammo":9,
         "ammoCapacity":5,
         "muzzleVelocityChange":0.05,
         "price":7500,
         "sound":"SFXRifle1"
      },{
         "name":4222,
         "type":24,
         "animatedWeapon":29,
         "range":1,
         "baseDamage":20,
         "armorNeutralization":2,
         "openWoundCoeficient":0.01,
         "weight":0.3,
         "price":40,
         "sound":["SFXPunch1","SFXPunch2","SFXPunch3","SFXPunch4","SFXPunch5"]
      },{
         "name":4223,
         "type":3,
         "animatedWeapon":20,
         "range":200,
         "accuracy":6,
         "weight":0.625,
         "ammo":1,
         "ammoCapacity":17,
         "muzzleVelocityChange":0.05,
         "price":5500,
         "sound":"SFXPistol1"
      },{
         "name":4225,
         "type":25,
         "animatedWeapon":21,
         "range":200,
         "accuracy":4,
         "weight":2.8,
         "ammo":3,
         "ammoCapacity":1,
         "muzzleVelocityChange":0.1,
         "spread":0.15,
         "price":10000,
         "sound":["SFXShotgun1","SFXShotgun2","SFXShotgun3"]
      },{
         "name":4227,
         "type":6,
         "animatedWeapon":21,
         "range":180,
         "accuracy":4,
         "weight":2.863,
         "ammo":3,
         "ammoCapacity":2,
         "muzzleVelocityChange":0,
         "spread":0.2,
         "price":12000,
         "sound":["SFXShotgun1","SFXShotgun2","SFXShotgun3"]
      },{
         "name":4228,
         "type":17,
         "animatedWeapon":21,
         "range":170,
         "accuracy":4,
         "weight":3.3,
         "ammo":3,
         "ammoCapacity":5,
         "muzzleVelocityChange":-0.05,
         "spread":0.25,
         "price":25000,
         "sound":["SFXShotgun1","SFXShotgun2","SFXShotgun3"]
      },{
         "name":4230,
         "type":11,
         "animatedWeapon":20,
         "range":200,
         "accuracy":6,
         "weight":1.25,
         "ammo":10,
         "ammoCapacity":6,
         "muzzleVelocityChange":0,
         "price":23000,
         "sound":"SFXRevolver1"
      },{
         "name":4234,
         "type":15,
         "animatedWeapon":28,
         "range":200,
         "accuracy":7,
         "weight":3.1,
         "ammo":11,
         "ammoCapacity":30,
         "muzzleVelocityChange":0,
         "price":30000,
         "sound":["SFXAK1","SFXAK2","SFXAK3"]
      },{
         "name":4237,
         "type":26,
         "animatedWeapon":30,
         "range":200,
         "accuracy":5,
         "weight":2.6,
         "ammo":12,
         "ammoCapacity":50,
         "muzzleVelocityChange":0.03,
         "price":54000,
         "sound":["SFXSMG1","SFXSMG2","SFXSMG3"]
      },{
         "name":5625,
         "type":9,
         "animatedWeapon":31,
         "range":100,
         "accuracy":7,
         "weight":5.9,
         "ammo":13,
         "ammoCapacity":6,
         "arrowSpeed":75,
         "price":700000,
         "sound":"SFXGrenadeLauncher1"
      },{
         "name":5630,
         "type":11,
         "animatedWeapon":20,
         "range":200,
         "accuracy":5,
         "weight":1.59,
         "ammo":14,
         "ammoCapacity":5,
         "muzzleVelocityChange":0,
         "price":98000,
         "sound":"SFXRevolver1"
      },{
         "name":6059,
         "type":16,
         "animatedWeapon":32,
         "range":1000,
         "accuracy":5,
         "weight":11.57,
         "ammo":15,
         "ammoCapacity":250,
         "muzzleVelocityChange":0,
         "price":150000,
         "sound":["SFXMachineGun1","SFXMachineGun2"]
      },{
         "name":6780,
         "type":27,
         "animatedWeapon":33,
         "range":1000,
         "accuracy":5,
         "weight":38.56,
         "ammo":16,
         "ammoCapacity":1500,
         "muzzleVelocityChange":0,
         "price":750000,
         "sound":["SFXMachineGun1","SFXMachineGun2"]
      },{
         "name":6814,
         "type":4,
         "animatedWeapon":21,
         "range":800,
         "accuracy":13,
         "weight":5.27,
         "ammo":16,
         "ammoCapacity":20,
         "muzzleVelocityChange":0.04,
         "price":600000,
         "sound":"SFXRifle1"
      }];
      
      public static var Ammo:* = [undefined,{
         "type":1,
         "variation":1076,
         "projectileMass":8.04,
         "FF":0.9,
         "muzzleVelocity":360,
         "armorPiercing":0.9,
         "softTargetDamage":1,
         "price":10,
         "weight":0.015
      },{
         "type":1,
         "variation":1077,
         "projectileMass":7.45,
         "FF":1,
         "muzzleVelocity":390,
         "armorPiercing":1,
         "softTargetDamage":1,
         "price":11,
         "weight":0.015
      },{
         "type":1,
         "variation":1078,
         "projectileMass":7.45,
         "FF":0.8,
         "muzzleVelocity":411,
         "armorPiercing":0.8,
         "softTargetDamage":1.3,
         "price":11,
         "weight":0.015
      },{
         "type":2,
         "variation":1079,
         "projectileMass":10.7,
         "FF":1.3,
         "muzzleVelocity":850,
         "armorPiercing":1,
         "softTargetDamage":1,
         "price":35,
         "weight":0.015
      },{
         "type":2,
         "variation":1080,
         "projectileMass":10.7,
         "FF":1.1,
         "muzzleVelocity":850,
         "armorPiercing":2,
         "softTargetDamage":0.7,
         "price":40,
         "weight":0.015
      },{
         "type":3,
         "variation":1081,
         "projectileMass":5.67,
         "FF":0.6,
         "muzzleVelocity":386,
         "armorPiercing":0.8,
         "softTargetDamage":1,
         "bulletDiameter":9.7,
         "pallets":6,
         "price":25,
         "weight":0.015
      },{
         "type":3,
         "variation":1082,
         "projectileMass":3.88,
         "FF":0.5,
         "muzzleVelocity":380,
         "armorPiercing":0.8,
         "softTargetDamage":1,
         "bulletDiameter":8.4,
         "pallets":9,
         "price":25.5,
         "weight":0.015
      },{
         "type":3,
         "variation":1083,
         "projectileMass":2.188,
         "FF":0.4,
         "muzzleVelocity":380,
         "armorPiercing":0.8,
         "softTargetDamage":1,
         "bulletDiameter":7.6,
         "pallets":16,
         "price":26.5,
         "weight":0.015
      },{
         "type":3,
         "variation":1084,
         "projectileMass":1.297,
         "FF":0.4,
         "muzzleVelocity":380,
         "armorPiercing":0.8,
         "softTargetDamage":1,
         "bulletDiameter":6,
         "pallets":27,
         "price":28,
         "weight":0.015
      },{
         "type":3,
         "variation":1085,
         "projectileMass":35.44,
         "FF":0.9,
         "muzzleVelocity":378,
         "armorPiercing":0.9,
         "softTargetDamage":1,
         "bulletDiameter":18.6,
         "pallets":1,
         "price":30,
         "weight":0.015
      },{
         "type":4,
         "variation":1086,
         "projectileMass":50,
         "FF":0.995,
         "armorPiercing":0.9,
         "softTargetDamage":1,
         "explosive":false,
         "price":15,
         "weight":0.05
      },{
         "type":5,
         "variation":1086,
         "projectileMass":0,
         "price":5,
         "weight":1,
         "flamethrower":true
      },{
         "type":6,
         "variation":1087,
         "projectileMass":0,
         "FF":0.99,
         "explosive":true,
         "explosiveness":50,
         "antiPersonnel":0,
         "price":5000,
         "weight":1.59
      },{
         "type":7,
         "variation":3891,
         "projectileMass":4.1,
         "FF":1.2,
         "muzzleVelocity":936,
         "armorPiercing":1.1,
         "softTargetDamage":0.9,
         "price":25,
         "weight":0.015
      },{
         "type":7,
         "variation":3892,
         "projectileMass":5,
         "FF":1.2,
         "muzzleVelocity":838,
         "armorPiercing":0.8,
         "softTargetDamage":1.2,
         "price":25,
         "weight":0.015
      },{
         "type":8,
         "variation":1077,
         "projectileMass":11.7,
         "FF":1,
         "muzzleVelocity":743,
         "armorPiercing":1.1,
         "softTargetDamage":0.8,
         "price":40,
         "weight":0.015
      },{
         "type":8,
         "variation":3892,
         "projectileMass":11.7,
         "FF":1.2,
         "muzzleVelocity":743,
         "armorPiercing":0.8,
         "softTargetDamage":1.5,
         "price":50,
         "weight":0.012
      },{
         "type":9,
         "variation":3892,
         "projectileMass":11.3,
         "FF":1.2,
         "muzzleVelocity":797,
         "armorPiercing":0.8,
         "softTargetDamage":1.5,
         "price":45,
         "weight":0.011
      },{
         "type":9,
         "variation":1077,
         "projectileMass":11.7,
         "FF":1,
         "muzzleVelocity":786,
         "armorPiercing":1.1,
         "softTargetDamage":1,
         "price":40,
         "weight":0.011
      },{
         "type":9,
         "variation":4182,
         "projectileMass":9.4,
         "FF":1,
         "muzzleVelocity":928,
         "armorPiercing":1.5,
         "softTargetDamage":0.7,
         "price":50,
         "weight":0.011
      },{
         "type":10,
         "variation":1078,
         "projectileMass":8.1,
         "FF":0.9,
         "muzzleVelocity":442,
         "armorPiercing":0.8,
         "softTargetDamage":1.3,
         "price":70,
         "weight":0.011
      },{
         "type":10,
         "variation":4231,
         "projectileMass":12,
         "FF":1,
         "muzzleVelocity":400,
         "armorPiercing":0.9,
         "softTargetDamage":1.1,
         "price":80,
         "weight":0.011
      },{
         "type":11,
         "variation":1077,
         "projectileMass":7.9,
         "FF":1,
         "muzzleVelocity":730,
         "armorPiercing":1.1,
         "softTargetDamage":0.9,
         "price":30,
         "weight":0.011
      },{
         "type":11,
         "variation":4233,
         "projectileMass":8.04,
         "FF":1,
         "muzzleVelocity":715,
         "armorPiercing":1.4,
         "softTargetDamage":0.8,
         "price":35,
         "weight":0.011
      },{
         "type":12,
         "variation":4182,
         "projectileMass":2,
         "FF":1,
         "muzzleVelocity":716,
         "armorPiercing":1.6,
         "softTargetDamage":0.8,
         "price":35,
         "weight":0.011
      },{
         "type":12,
         "variation":1078,
         "projectileMass":2,
         "FF":1,
         "muzzleVelocity":716,
         "armorPiercing":1.1,
         "softTargetDamage":1.2,
         "price":30,
         "weight":0.011
      },{
         "type":13,
         "variation":5627,
         "projectileMass":0,
         "FF":0.99,
         "explosive":true,
         "explosiveness":40,
         "antiPersonnel":0,
         "price":8000,
         "weight":0.7
      },{
         "type":13,
         "variation":5628,
         "projectileMass":0,
         "FF":0.99,
         "explosive":true,
         "explosiveness":30,
         "antiPersonnel":10,
         "price":9000,
         "weight":0.7
      },{
         "type":14,
         "variation":1078,
         "projectileMass":17.8,
         "FF":0.9,
         "muzzleVelocity":507,
         "armorPiercing":0.8,
         "softTargetDamage":1.2,
         "price":250,
         "weight":0.018
      },{
         "type":14,
         "variation":5631,
         "projectileMass":23,
         "FF":0.9,
         "muzzleVelocity":430,
         "armorPiercing":1.1,
         "softTargetDamage":0.9,
         "price":270,
         "weight":0.023
      },{
         "type":15,
         "variation":6061,
         "projectileMass":12.8,
         "FF":1,
         "muzzleVelocity":800,
         "armorPiercing":1,
         "softTargetDamage":1,
         "price":200,
         "weight":0.023
      },{
         "type":16,
         "variation":6783,
         "projectileMass":10,
         "FF":1,
         "muzzleVelocity":833,
         "armorPiercing":1,
         "softTargetDamage":1,
         "price":90,
         "weight":0.023
      },{
         "type":16,
         "variation":6784,
         "projectileMass":11,
         "FF":1,
         "muzzleVelocity":790,
         "armorPiercing":0.8,
         "softTargetDamage":1.4,
         "price":125,
         "weight":0.023
      }];
      
      public static var Calibers:* = [undefined,{
         "name":292,
         "bulletDiameter":9.03,
         "caseAndPropellantWeight":4.34
      },{
         "name":293,
         "bulletDiameter":7.8,
         "caseAndPropellantWeight":16.6
      },{
         "name":294,
         "caseAndPropellantWeight":15,
         "shotgun":true
      },{
         "name":295,
         "bulletDiameter":13,
         "caseAndPropellantWeight":0,
         "arrow":true
      },{
         "name":296,
         "caseAndPropellantWeight":10
      },{
         "name":297,
         "caseAndPropellantWeight":2000
      },{
         "name":3890,
         "bulletDiameter":5.7,
         "caseAndPropellantWeight":7.8
      },{
         "name":4176,
         "bulletDiameter":7.9,
         "caseAndPropellantWeight":13
      },{
         "name":4181,
         "bulletDiameter":7.92,
         "caseAndPropellantWeight":12.2
      },{
         "name":4229,
         "bulletDiameter":9.1,
         "caseAndPropellantWeight":8.2
      },{
         "name":4232,
         "bulletDiameter":9.1,
         "caseAndPropellantWeight":8.4
      },{
         "name":4235,
         "bulletDiameter":5.7,
         "caseAndPropellantWeight":4
      },{
         "name":5626,
         "caseAndPropellantWeight":1200
      },{
         "name":5629,
         "bulletDiameter":9.1,
         "caseAndPropellantWeight":12
      },{
         "name":6060,
         "bulletDiameter":8.08,
         "caseAndPropellantWeight":18
      },{
         "name":6782,
         "bulletDiameter":7.82,
         "caseAndPropellantWeight":13
      }];
      
      public static var Attachments:* = [undefined,{
         "name":1053,
         "type":1,
         "applicable":["rifle","crossbow"],
         "affectAccuracy":1,
         "scope":true,
         "description":6815,
         "weight":0.35,
         "price":90000
      },{
         "name":5735,
         "type":1,
         "applicable":["pistol"],
         "affectAccuracy":1,
         "description":6815,
         "scope":true,
         "weight":0.5,
         "price":120000
      },{
         "name":6816,
         "type":1,
         "applicable":["rifle","crossbow"],
         "affectAccuracy":2,
         "description":6815,
         "scope":true,
         "weight":0.45,
         "price":650000
      },{
         "name":6817,
         "type":1,
         "applicable":["rifle","crossbow"],
         "affectAccuracy":3,
         "description":6815,
         "scope":true,
         "weight":0.66,
         "price":1200000
      },{
         "name":6818,
         "type":2,
         "applicable":["pistol","rifle"],
         "affectAccuracy":1,
         "description":6822,
         "laser":true,
         "batteries":1,
         "weight":0.25,
         "price":200000
      },{
         "name":6825,
         "type":1,
         "applicable":["rifle"],
         "affectAccuracy":4,
         "description":6815,
         "scope":true,
         "batteries":4,
         "weight":0.75,
         "price":2500000
      }];
      
      public function WeaponsData()
      {
         super();
      }
      
      public static function getWeaponDescription(param1:*, param2:* = true) : *
      {
         var _loc3_:String = "";
         var _loc4_:* = WeaponTypes[Weapons[param1].type];
         _loc3_ += Texts.fetch(198) + ": " + Texts.fetch(_loc4_.name) + "\n";
         if(_loc4_.category == 2 || _loc4_.category == 3 || _loc4_.category == 4)
         {
            _loc3_ += Texts.fetch(298) + ": " + Texts.fetch(Calibers[Weapons[param1].ammo].name) + "\n";
            _loc3_ += Texts.fetch(299) + ": " + Weapons[param1].ammoCapacity + "\n";
            _loc3_ += Texts.fetch(300) + ": " + Weapons[param1].accuracy + "\n";
         }
         if(_loc4_.category == 2)
         {
            _loc3_ += Texts.fetch(301) + ": " + Math.round((Weapons[param1].muzzleVelocityChange + 1) * 100) + "%\n";
         }
         if(_loc4_.category == 3)
         {
            _loc3_ += Texts.fetch(302) + ": " + Weapons[param1].arrowSpeed + "\n";
         }
         if(_loc4_.category == 1)
         {
            _loc3_ += Texts.fetch(303) + ": " + Weapons[param1].baseDamage + "\n";
            _loc3_ += Texts.fetch(304) + ": " + Weapons[param1].armorNeutralization + "\n";
            _loc3_ += Texts.fetch(305) + ": " + Math.round(Weapons[param1].openWoundCoeficient * 1000) + "\n";
         }
         if(_loc4_.category == 5)
         {
            _loc3_ += Texts.fetch(306) + ": " + Weapons[param1].explosiveness + "\n";
            _loc3_ += Texts.fetch(307) + ": " + Weapons[param1].antiPersonnel + "\n";
         }
         return _loc3_;
      }
      
      public static function getWeaponIcon(param1:*) : *
      {
         var _loc2_:* = param1;
         if(Weapons[param1].icon != null)
         {
            _loc2_ = Weapons[param1].icon;
         }
         return new ImportedBitmap("weaponIcon" + _loc2_ + ".png");
      }
      
      public static function detectWeaponSkill(param1:*) : *
      {
         var _loc2_:* = WeaponTypes[param1.type];
         if(_loc2_.category == 0 || param1.type == 24)
         {
            return "unarmed";
         }
         if(_loc2_.category == 1)
         {
            switch(param1.type)
            {
               case 1:
                  return "knives";
               case 2:
                  return "clubs";
               case 19:
                  return "chopping";
               case 20:
                  return "swords";
            }
         }
         if(_loc2_.category == 3)
         {
            switch(_loc2_.subCategory)
            {
               case 1:
                  return "crossbow";
               case 2:
                  return "rocketLauncher";
            }
         }
         if(_loc2_.category == 2)
         {
            switch(_loc2_.subCategory)
            {
               case 1:
                  return "pistol";
               case 2:
                  return "rifle";
               case 3:
                  return "machinegun";
               case 4:
                  return "smg";
               case 5:
                  return "shotgun";
            }
         }
         if(_loc2_.category == 4)
         {
            return "flamethrower";
         }
         if(_loc2_.category == 5)
         {
            return "throw";
         }
      }
   }
}

